---
- name: Check Results
  gather_facts: true
  hosts: localhost
  tasks:

    - name: Show Output
      ansible.builtin.debug:
        msg: "Real:{{ timestamp }} Execution:{{ execution_timestamp }}"

    - name: Show Output
      ansible.builtin.fail:
        msg: "Real:{{ timestamp }} Execution:{{ execution_timestamp }}"
      when: timestamp != execution_timestamp

    - name: Relaunch Job
      ansible.controller.workflow_launch:
        workflow_template: "Test Pipeline"
        validate_certs: false
        wait: false
