---
- name: Check Results
  gather_facts: true
  hosts: localhost
  tasks:

    - name: Show Output
      ansible.builtin.debug:
        msg: "Real:{{ lookup('vars', sync_job_id + '_timestamp') }} Execution: {{ lookup('vars', sync_job_id + '_execution_timestamp') }}"

    - name: Show Output
      ansible.builtin.fail:
        msg: "Real:{{ lookup('vars', sync_job_id + '_timestamp') }} Execution:{{ lookup('vars', sync_job_id + '_execution_timestamp') }}"
      when: lookup('vars', sync_job_id + '_timestamp') != lookup('vars', sync_job_id + '_execution_timestamp')

    - name: Relaunch Job
      ansible.controller.workflow_launch:
        workflow_template: "HSBC_Reproducer"
        validate_certs: false
        wait: false
