---
- name: Perform a change in the repository
  gather_facts: true
  hosts: localhost
  tasks:
    - name: Get the Timestamp
      ansible.builtin.set_fact:
        timestamp: "{{ ansible_date_time.iso8601_basic }}"

    - name: Download Test Role Git Repository
      ansible.builtin.include_role:
        name: ansible_automation_platform.zaskan.git
      vars:
        git_operation: "clone"
        git_repository: "git@github.com:zaskan/test_role.git"
        git_directory: "/tmp/test_role"
        git_key_path: "{{ lookup('env', 'PRIVATE_KEY') }}"
      
    - name: Download THIS Git Repository
      ansible.builtin.include_role:
        name: ansible_automation_platform.zaskan.git
      vars:
        git_operation: "clone"
        git_repository: "git@github.com:zaskan/nodes_sync_lab.git"
        git_directory: "/tmp/nodes_sync_lab"
        git_key_path: "{{ lookup('env', 'PRIVATE_KEY') }}"

    - name: Perform a change in the code
      ansible.builtin.lineinfile:
        path: /tmp/test_role/tasks/main.yml
        regexp: '^      fact: "'
        line: '      fact: "{{ timestamp }}"'

    - name: Push Changes
      ansible.builtin.include_role:
        name: ansible_automation_platform.zaskan.git
      vars:
        git_operation: "push"
        git_repository: "git@github.com:zaskan/test_role.git"
        git_directory: "/tmp/test_role"
        git_message: "{{ timestamp }}"
        git_email: "rafsanch@redhat.com"
        git_user: "rafsanch"
        git_key_path: "{{ lookup('env', 'PRIVATE_KEY') }}"

    - name: Get current commit
      ansible.builtin.command: "/usr/bin/git rev-parse HEAD"
      args:
        chdir: /tmp/test_role/
      changed_when: commit.rc == 0
      register: commit

    - name: Update requirements file
      ansible.builtin.lineinfile:
        path: /tmp/nodes_sync_lab/roles/requirements.yml
        regexp: '^    version: '
        line: '    version: "{{ commit.stdout }}"'

    - name: Push Changes
      ansible.builtin.include_role:
        name: ansible_automation_platform.zaskan.git
      vars:
        git_operation: "push"
        git_repository: "git@github.com:zaskan/nodes_sync_lab.git"
        git_directory: "/tmp/nodes_sync_lab"
        git_message: "{{ timestamp }}"
        git_email: "rafsanch@redhat.com"
        git_user: "rafsanch"
        git_key_path: "{{ lookup('env', 'PRIVATE_KEY') }}"

    - name: Project Sync
      ansible.controller.project_update:
        project: "nodes_sync_lab"
        wait: true
        validate_certs: false
        
    - name: Trigger Cleanup Job
      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}/api/v2/system_job_templates/1/launch/"
        user: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        method: POST
        force_basic_auth: true
        status_code: 202
        body_format: json
        body: '{"extra_vars": {"days": 0}}'
        validate_certs: false

    - name: Set the Timestamp
      ansible.builtin.set_stats:
        data:
          timestamp: "{{ timestamp }}"

    - name: Save Job Environment
      ansible.builtin.command: 'env'
      changed_when: sync_job_id.rc == 0
      register: sync_job_id

    - name: Set the Timestamp
      ansible.builtin.set_stats:
        data:
          sync_job_id: "{{ sync_job_id }}"
