---
- name: Perform a change in the repository
  gather_facts: true
  hosts: localhost
  tasks:
    - name: Get the Timestamp
      ansible.builtin.set_fact:
        timestamp: "{{ ansible_date_time.iso8601_basic }}"

    - name: Download Git Repository
      ansible.builtin.include_role:
        name: ansible_automation_platform.zaskan.git
      vars:
        git_operation: "clone"
        git_repository: "git@github.com:zaskan/test_role.git"
        git_directory: "/tmp/test_role"
        git_key_path: "{{ lookup('env', 'PRIVATE_KEY') }}"

    - name: Perform a change in the code
      ansible.builtin.lineinfile:
        path: /tmp/test_role/tasks/main.yml
        regexp: '^      fact: "'
        line: '      fact: "{{ timestamp }}"'

    - name: Push Changes
      ansible.builtin.include_role:
        name: ansible_automation_platform.zaskan.git
      vars:
        git_operation: "push"
        git_repository: "git@github.com:zaskan/test_role.git"
        git_directory: "/tmp/test_role"
        git_message: "{{ timestamp }}"
        git_email: "rafsanch@redhat.com"
        git_user: "rafsanch"
        git_key_path: "{{ lookup('env', 'PRIVATE_KEY') }}"

    - name: Set the Timestamp
      ansible.builtin.set_stats:
        data:
          timestamp: "{{ timestamp }}"
